# Generated by Django 3.0 on 2019-12-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=200)),
                ('name', models.CharField(max_length=5)),
                ('design', models.IntegerField(default=0)),
                ('gift', models.IntegerField(default=0)),
                ('receiver', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=100)),
                ('sentAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-sentAt'],
            },
        ),
    ]
