# Generated by Django 3.0.7 on 2020-12-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
