# Generated by Django 3.0 on 2019-12-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='pw',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='letter',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='letter',
            name='name',
            field=models.CharField(max_length=8),
        ),
    ]
