# Generated by Django 3.0 on 2019-12-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0002_auto_20191229_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='sender',
        ),
        migrations.AlterField(
            model_name='letter',
            name='pw',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
