# Generated by Django 3.0.1 on 2019-12-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0003_auto_20191230_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='pw',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
