# Generated by Django 3.0.7 on 2020-11-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0004_auto_20191230_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='pw',
        ),
    ]
