# Generated by Django 3.0.7 on 2020-12-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0005_remove_letter_pw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('img', models.URLField()),
                ('sendimg', models.URLField()),
            ],
        ),
    ]
