# Generated by Django 3.0.7 on 2020-12-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0007_auto_20201205_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gift',
            name='sendimg',
            field=models.TextField(),
        ),
    ]
