# Generated by Django 3.0.7 on 2020-12-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0008_auto_20201205_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='img',
            field=models.TextField(),
        ),
    ]
