# Generated by Django 3.0.7 on 2020-12-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0009_auto_20201205_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='sendimg',
        ),
    ]
